In [1]:
import pandas as pd
import numpy as np

In [2]:
df_candiates = pd.read_csv(r'C:\Users\DELL\Documents\Skill sync\datasets\upwork_data_scientists.csv')
df_candiates.columns = df_candiates.columns.str.strip()
df_candiates.tail()

,country,description,hourlyRate,jobSuccess,locality,name,skills,title,totalHours,totalJobs,ExperienceLevel
129,Bangladesh,Top Rated 🏆 @upwork\n100% Job Success$50k+ Tot...,6.0,97%,Jessore,Antu C.,Data Entry|Data Extraction|List Building|Data ...,"B2B Email Finder, Business Email Lookup, Email...",531.0,219.0,NaN
130,Morocco,Specialized in Process Automation. (Minimize d...,50.0,100%,Casablanca,Adnane R.,Python|Business Process Automation|UiPath|Java...,"Automation & AI Expert (Python, GPT, ML, Excel...",100.0,24.0,NaN
131,India,Top Rated 🏆\n- Proven Track Record 🏆- 5-star r...,20.0,100%,Dehradun,Parthsarthi D.,Graphic Design|YouTube Marketing|Social Media ...,Expert Social Media Manager | Youtube | Instag...,253.0,160.0,NaN
132,India,good in machine learning,10.5,95.0,sirsaganj,NaN,"Machine learning , deep learning , genai",Machine Learning,200.0,30.0,Mid-Senior
133,India,good in machine learning,10.5,95.0,sirsaganj,AMABAR,"Machine learning , deep learning , genai",Machine Learning,200.0,30.0,Mid-Senior

In [3]:
df_jobs = pd.read_csv(r'C:\Users\DELL\Documents\Skill sync\datasets\job_dataset.csv')
df_jobs.columns = df_jobs.columns.str.strip()
df_jobs.tail()

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords
1067,WEB-E-020,Web Developer,Experienced,5+,JavaScript; TypeScript; Angular; Node.js; Expr...,Lead Angular front-end development; Develop No...,Angular; Node.js; Express.js; SQL; Redis; Dock...
1068,J-101010,NaN,Fresher,NaN,"Machine learning , deep learning , llm",will work on sentiment analysis,"machine leaning , sentiment analysis"
1069,J-101010,NaN,Fresher,NaN,"Machine learning , deep learning , llm",will work on sentiment analysis,"machine leaning , sentiment analysis"
1070,J-10102,NaN,Fresher,NaN,"Machine learning , deep learning , llm , NLP ,...",will work on sentiment analysis,"machine leaning , sentiment analysis"
1071,j- 101,web development,Experienced,2 - 3,"html , css ,react",hav eto built a e-commerce website,"html , css ,react"

In [4]:
df_candiates.isnull().sum()

country              4
description          0
hourlyRate           0
jobSuccess          13
locality             0
name                 1
skills               0
title                0
totalHours           9
totalJobs            0
ExperienceLevel    132
dtype: int64

In [5]:
df_candiates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          130 non-null    object
 1   description      134 non-null    object
 2   hourlyRate       134 non-null    float64
 3   jobSuccess       121 non-null    object
 4   locality         134 non-null    object
 5   name             133 non-null    object
 6   skills           134 non-null    object
 7   title            134 non-null    object
 8   totalHours       125 non-null    float64
 9   totalJobs        134 non-null    float64
 10  ExperienceLevel  2 non-null      object
dtypes: float64(3), object(8)
memory usage: 11.6+ KB

In [6]:
df_candiates['jobSuccess'] = df_candiates['jobSuccess'].str.split('%').str[0].astype(float)

In [7]:
df_candiates['totalHours'].fillna(df_candiates['totalHours'].mean(), inplace=True)
df_candiates['jobSuccess'].fillna(df_candiates['jobSuccess'].mean(), inplace=True)
df_candiates['country'].fillna(df_candiates['country'].mode()[0], inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_13832\3751134155.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_candiates['totalHours'].fillna(df_candiates['totalHours'].mean(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_13832\3751134155.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_candiates['jobSuccess'].fillna(df_candiates['jobSuccess'].mean(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_13832\3751134155.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_candiates['country'].fillna(df_candiates['country'].mode()[0], inplace=True)

In [8]:
df_jobs.isnull().sum()

JobID                0
Title                4
ExperienceLevel      0
YearsOfExperience    3
Skills               0
Responsibilities     0
Keywords             0
dtype: int64

In [9]:
df_jobs.dropna(inplace=True)

In [10]:
df_candiates

,country,description,hourlyRate,jobSuccess,locality,name,skills,title,totalHours,totalJobs,ExperienceLevel
0,Egypt,let the work of data for me 📊 and get the busi...,25.0,97.0,Giza,Abeer K.,Python|Machine Learning|Scrapy|Data Science|SQ...,Data Scientist | Web Scraping Engineer,405.0,69.0,NaN
1,Serbia,I am master environmental protection analyst a...,15.0,97.0,Belgrade,Nikola M.,Data Entry|Google Docs|Online Research|Lead Ge...,Researcher,354.0,68.0,NaN
2,Philippines,Specializes in automated Excel solutions that ...,60.0,100.0,Manila,"Ramil, Jr. A.",Microsoft Excel|Excel Formula|Excel Macros|Vis...,Excel | VBA | Macros | Google Sheets Expert,15.0,351.0,NaN
3,United States,Data Science and Machine Learning Expert for H...,500.0,100.0,Wyckoff,Jason K.,Deep Learning|Python|Data Science|Machine Lear...,Data Science & AI Expert- Senior Machine Learn...,434.0,80.0,NaN
4,Pakistan,"🔴🟡🔴🟡🔴🟡🔴🟡🔴🟡🟡🟡🟡🟡🟡🟡"" I can do anything with Pytho...",25.0,82.0,Karachi,Muhammad Noman B.,Data Science|Machine Learning|pandas|Microsoft...,Data Science | Python Projects | Machine Learn...,4.0,11.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
129,Bangladesh,Top Rated 🏆 @upwork\n100% Job Success$50k+ Tot...,6.0,97.0,Jessore,Antu C.,Data Entry|Data Extraction|List Building|Data ...,"B2B Email Finder, Business Email Lookup, Email...",531.0,219.0,NaN
130,Morocco,Specialized in Process Automation. (Minimize d...,50.0,100.0,Casablanca,Adnane R.,Python|Business Process Automation|UiPath|Java...,"Automation & AI Expert (Python, GPT, ML, Excel...",100.0,24.0,NaN
131,India,Top Rated 🏆\n- Proven Track Record 🏆- 5-star r...,20.0,100.0,Dehradun,Parthsarthi D.,Graphic Design|YouTube Marketing|Social Media ...,Expert Social Media Manager | Youtube | Instag...,253.0,160.0,NaN
132,India,good in machine learning,10.5,95.0,sirsaganj,NaN,"Machine learning , deep learning , genai",Machine Learning,200.0,30.0,Mid-Senior
133,India,good in machine learning,10.5,95.0,sirsaganj,AMABAR,"Machine learning , deep learning , genai",Machine Learning,200.0,30.0,Mid-Senior

In [11]:
df_jobs

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords
0,NET-F-001,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Framework; .NET Core f...,Assist in coding and debugging applications; L...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
1,NET-F-002,.NET Developer,Fresher,0-1,C#; .NET Framework basics; ASP.NET; Razor; HTM...,Write simple C# programs under guidance; Suppo...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
2,NET-F-003,.NET Developer,Fresher,0-1,C#; VB.NET basics; .NET Core; ASP.NET MVC; HTM...,Contribute to development of small modules; As...,.NET; C#; ASP.NET MVC; SQL Server; Entity Fram...
3,NET-F-004,.NET Developer,Fresher,0-1,C#; .NET Framework; ASP.NET basics; SQL Server...,Support in software design documentation; Assi...,.NET; C#; SQL Server; Entity Framework; ASP.NET
4,NET-F-005,.NET Developer,Fresher,0-1,C#; ASP.NET; MVC; Entity Framework basics; SQL...,Learn to design and build ASP.NET applications...,.NET; C#; ASP.NET MVC; Entity Framework; SQL S...
...,...,...,...,...,...,...,...
1064,WEB-E-017,Web Developer,Experienced,4+,JavaScript; TypeScript; React; Node.js; Expres...,Develop and maintain full stack applications; ...,React; Node.js; Express.js; SQL; MongoDB; Dock...
1065,WEB-E-018,Web Developer,Experienced,5+,JavaScript; Vue.js; Node.js; Express.js; SQL; ...,Lead Vue.js front-end development; Integrate N...,Vue.js; Node.js; Express.js; SQL; Redis; Docke...
1066,WEB-E-019,Web Developer,Experienced,4+,JavaScript; React; Node.js; Express.js; MongoD...,Develop complex web applications; Integrate Re...,React; Node.js; Express.js; MongoDB; Docker; K...
1067,WEB-E-020,Web Developer,Experienced,5+,JavaScript; TypeScript; Angular; Node.js; Expr...,Lead Angular front-end development; Develop No...,Angular; Node.js; Express.js; SQL; Redis; Dock...
1071,j- 101,web development,Experienced,2 - 3,"html , css ,react",hav eto built a e-commerce website,"html , css ,react"

In [12]:
df_jobs['ExperienceLevel'].value_counts()

ExperienceLevel
Experienced         477
Fresher             363
Entry-Level          66
Senior-Level         65
Mid-Level            60
Senior               15
Lead                  7
Junior                5
Mid-level             5
Mid-Senior Level      3
Mid-Senior            2
Name: count, dtype: int64

In [13]:
df_jobs["ExperienceLevel"] = df_jobs["ExperienceLevel"].str.strip().str.lower()

In [14]:
experience_map = {
    "fresher": "Fresher",
    "entry-level": "Fresher",

    "junior": "Junior",

    "mid-level": "Mid",
    "mid-level ": "Mid",
    "mid-level": "Mid",

    "mid-senior level": "Mid-Senior",
    "mid-senior": "Mid-Senior",

    "senior": "Senior",
    "senior-level": "Senior",
    "lead": "Senior",

    "experienced": "Experienced"
}

df_jobs["ExperienceLevel"] = df_jobs["ExperienceLevel"].map(experience_map)

In [15]:
def get_experience_level(hours, jobs):

    score = hours + (jobs * 20)

    if score <= 200:
        return "Fresher"
    
    elif score <= 800:
        return "Junior"
    
    elif score <= 2500:
        return "Mid"
    
    elif score <= 6000:
        return "Senior"
    
    else:
        return "Experienced"


df_candiates["ExperienceLevel"] = df_candiates.apply(
    lambda row: row["ExperienceLevel"]
    if pd.notna(row["ExperienceLevel"])
    else get_experience_level(row["totalHours"], row["totalJobs"]),
    axis=1
)

In [18]:
import emoji

def remove_emoji(text):
    return emoji.replace_emoji(text, replace='')

In [19]:
df_candiates['description'] = df_candiates['description'].apply(remove_emoji)
df_candiates['title'] = df_candiates['title'].str.replace('|' , ' ')
df_candiates['skills'] = df_candiates['skills'].str.replace('|' , ' ')
df_jobs['Skills'] = df_jobs['Skills'].str.replace(';' , ' ')
df_jobs['Keywords'] = df_jobs['Keywords'].str.replace(';' , ' ')
df_jobs['Responsibilities'] = df_jobs['Responsibilities'].str.replace(';' , ' ')

In [20]:
df_candiates.to_csv("C:\\Users\\DELL\\Documents\\Skill sync\\datasets\\preprocessed_datasets\\candidates_preprocessed.csv", index=False)
df_jobs.to_csv("C:\\Users\\DELL\\Documents\\Skill sync\\datasets\\preprocessed_datasets\\jobs_preprocessed.csv", index=False)

In [21]:
df_candiates['profile_text'] = (df_candiates['title'] + ' ' + df_candiates['description'] + ' ' + df_candiates['skills'] + ' ' + df_candiates['ExperienceLevel'])
df_jobs['job_text'] = (df_jobs['Title'] + ' ' + df_jobs['Skills'] + ' ' + df_jobs['Responsibilities'] + ' ' + df_jobs['Keywords'] + ' ' + df_jobs['ExperienceLevel'])

In [22]:
df_candiates.head()

,country,description,hourlyRate,jobSuccess,locality,name,skills,title,totalHours,totalJobs,ExperienceLevel,profile_text
0,Egypt,let the work of data for me and get the busin...,25.0,97.0,Giza,Abeer K.,Python Machine Learning Scrapy Data Science SQ...,Data Scientist Web Scraping Engineer,405.0,69.0,Mid,Data Scientist Web Scraping Engineer let the...
1,Serbia,I am master environmental protection analyst a...,15.0,97.0,Belgrade,Nikola M.,Data Entry Google Docs Online Research Lead Ge...,Researcher,354.0,68.0,Mid,Researcher I am master environmental protectio...
2,Philippines,Specializes in automated Excel solutions that ...,60.0,100.0,Manila,"Ramil, Jr. A.",Microsoft Excel Excel Formula Excel Macros Vis...,Excel VBA Macros Google Sheets Expert,15.0,351.0,Experienced,Excel VBA Macros Google Sheets Expert Sp...
3,United States,Data Science and Machine Learning Expert for H...,500.0,100.0,Wyckoff,Jason K.,Deep Learning Python Data Science Machine Lear...,Data Science & AI Expert- Senior Machine Learn...,434.0,80.0,Mid,Data Science & AI Expert- Senior Machine Learn...
4,Pakistan,""" I can do anything with Python ""Noman is a So...",25.0,82.0,Karachi,Muhammad Noman B.,Data Science Machine Learning pandas Microsoft...,Data Science Python Projects Machine Learn...,4.0,11.0,Junior,Data Science Python Projects Machine Learn...

In [23]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [24]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    
    if not isinstance(text, str):
        return ""
    
    # lowercase
    text = text.lower()
    
    # remove unwanted characters but keep + # .
    text = re.sub(r"[^a-zA-Z0-9+#.\s]", " ", text)
    
    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    # tokenization
    tokens = word_tokenize(text)
    
    # remove stopwords
    tokens = [word for word in tokens if word not in stop_words]
    
    # lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    
    # join back
    return " ".join(tokens)

In [25]:
df_candiates['profile_text'] = df_candiates['profile_text'].apply(clean_text)
df_jobs['job_text'] = df_jobs['job_text'].apply(clean_text)

In [29]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

job_embeddings = model.encode(df_jobs["job_text"].tolist()).astype("float32")
candidate_embeddings = model.encode(df_candiates["profile_text"].tolist()).astype("float32")

In [30]:
import faiss

faiss.normalize_L2(job_embeddings)
faiss.normalize_L2(candidate_embeddings)

In [31]:
# for candidates embedding -> save to FAISS vector database
dimension = candidate_embeddings.shape[1]
candidate_index = faiss.IndexFlatIP(dimension)
candidate_index.add(candidate_embeddings)


faiss.write_index(candidate_index, "C:\\Users\\DELL\\Documents\\Skill sync\\embeddings\\candidate_index.faiss")

In [32]:
# for job embeddings -> save to FAISS vector database
job_index = faiss.IndexFlatIP(dimension)
job_index.add(job_embeddings)

faiss.write_index(job_index, "C:\\Users\\DELL\\Documents\\Skill sync\\embeddings\\job_index.faiss")

In [35]:
df = pd.read_csv(r"C:\Users\DELL\Documents\Skill sync\datasets\preprocessed_datasets\jobs_preprocessed.csv")
df.tail()

,JobID,Title,ExperienceLevel,YearsOfExperience,Skills,Responsibilities,Keywords
1065,WEB-E-019,Web Developer,Experienced,4+,JavaScript React Node.js Express.js MongoD...,Develop complex web applications Integrate Re...,React Node.js Express.js MongoDB Docker K...
1066,WEB-E-020,Web Developer,Experienced,5+,JavaScript TypeScript Angular Node.js Expr...,Lead Angular front-end development Develop No...,Angular Node.js Express.js SQL Redis Dock...
1067,j- 101,web development,Experienced,2 - 3,"html , css ,react",hav eto built a e-commerce website,"html , css ,react"
1068,j- 10056,NaN,Fresher,0- 1,"HTML, CSS, JavaScript, React.js, Node.js, Expr...","Develop and maintain web applications, Design ...","HTML, CSS, JavaScript, React.js, Node.js, Expr..."
1069,10045,web develop,Fresher,9,"HTML, CSS, JavaScript, React.js, Node.js, Expr...","Develop and maintain web applications, Design ...","HTML, CSS, JavaScript, React.js, Node.js, Expr..."